# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LKPeerTravel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking','3.1.0'
  pod 'SDWebImage','4.2.3’
  pod 'RealReachability'        #网络检测工具#
  pod 'MBProgressHUD'           #提示工具#
  pod 'UAAppReviewManager'      #appStore评分工具#
  pod 'Masonry'
  pod 'MJRefresh'               #上下拉刷新组件#
  pod 'SDCycleScrollView'        #自动轮番图工具#
  pod 'TTTAttributedLabel'     #带解析标签的UILabel#

  pod 'WechatOpenSDK','1.8.2'  #微信分享、登录、支付#

  pod 'YYKit','1.0.9'
  pod 'MJExtension','3.0.15'    #自动布局#
  
  pod 'FSCalendar','2.7.9'      #日历控件#
  
  pod 'Bugly'
  
  pod 'UMCCommon'
  pod 'UMCAnalytics'
  pod 'UMCSecurityPlugins'
  
  # Pods for LKPeerTravel

  target 'LKPeerTravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LKPeerTravelUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
          end
      end
  end

end
